apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: snyk-run-
spec:
  pipelineRef:
    name: snyk-pipeline
  params:
    - name: gitUrl
      value: https://github.com/<github_username>/goof-rhpds.git
    - name: gitRevision
      value: develop
    - name: pathToYamlFile
      value: "manifests/goof.yaml"
    - name: imageUrl
      value: quay.io/<quay_username>/goof
    - name: imageTag
      value: "latest" 
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: snyk-pvc
