apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: snyk-run-
spec:
  pipelineRef:
    name: snyk-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: snyk-pvc
